/**
 * Production site URL and brand name for SEO and shared config.
 *
 * Used from app code (JSON-LD, links). `astro.config.mjs` sets the same production `site` for builds.
 * Update `public/robots.txt` when the domain changes; sitemaps are generated by `@astrojs/sitemap`.
 * `PUBLIC_PHONE_E164` / `PUBLIC_EMAIL` match the footer and are safe for JSON-LD.
 */
export const SITE_URL = "https://truebridgetherapy.com" as const;
export const SITE_NAME = "TrueBridge" as const;

/** Public contact values (same as site footer). Used in JSON-LD where appropriate. */
export const PUBLIC_PHONE_E164 = "+19842076172" as const;
export const PUBLIC_PHONE_DISPLAY = "984-207-6172" as const;
export const PUBLIC_EMAIL = "info@truebridgetherapy.com" as const;
